### ISSUE TITLE
Package search doesn't find any matches for 'rockstar'

### ISSUE THREAD

**Issue by dylanbeattie** [paxromana96/sublime-rockstar-syntax#1]
The README says you should be able to install this by:

> Open the Command Palette (Ctrl+Shift+P or Tools -> Command Palette). Select "Install Package", then search for this package by typing "Rockstar".

This isn't working for me (Sublime 3.1.1 on macOS Sierra 10.12.16) - I get the command palette, it brings up the package search but the search string 'Rockstar' doesn't match anything.

**Comment by dylanbeattie** [comment]
I've tested it via the ZIP download and it works - and it is pretty awesome. Nice work. :)

**Comment by kennethgoodman** [comment]
I do not get any search results either, update does not work

**Comment by brownian-motion** [comment]
@dylanbeattie Thanks for the feedback! I'm glad you like it.

When I first submitted the package to package control, it took a few days of review before it showed up in Sublime. Is it there now, or are you still having trouble finding it?
